name: Deploy
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

env:
  PROJECT_ID: 'developer-fashionunited-com'
  
permissions: 
  contents: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
            node-version: 20 

      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: npm
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: Add AppMap language agent and appmap.yml"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: astro-dist
          path: dist

  deploy-folder-to-gcs-bucket:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
    
    - name: download-artifact
      uses: actions/download-artifact@v2
      with:
        name: astro-dist
        path: dist
    
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'dist'
        destination: 'developer.fashionunited.com'
        parent: false 
